DROP TABLE IF EXISTS gongjian;
DROP TABLE IF EXISTS post;

CREATE TABLE gongjian (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  huahen INTEGER NOT NULL,
  youwu INTEGER NOT NULL,
  angle FLOAT NOT NULL,
  circle INTEGER NOT NULL,
  lenth FLOAT NOT NULL,
  hege INTEGER NOT NULL,
  address TEXT UNIQUE NOT NULL,
  created datetime NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);